export const EMOJI_CONTENTS = [
  {
    id: 1,
    name: 'troll',
    describe: 'Troll',
    img: '/emoji/1.gif',
    length: 115,
  },
  {
    id: 2,
    name: 'onion',
    describe: 'Củ tỏi',
    img: '/emoji/2.gif',
    length: 112,
  },
  {
    id: 3,
    name: 'bafu',
    describe: 'Bafu',
    img: '/emoji/3.gif',
    length: 58,
  },
  {
    id: 4,
    name: 'thobua',
    describe: 'Thỏ bựa',
    img: '/emoji/4.gif',
    length: 99,
  },
  {
    id: 5,
    name: 'thotuzki',
    describe: 'Thỏ tự kỉ',
    img: '/emoji/5.gif',
    length: 60,
  },
  {
    id: 6,
    name: 'khiyoyo',
    describe: 'Khỉ yoyo',
    img: '/emoji/6.gif',
    length: 198,
  },
  {
    id: 7,
    name: 'gaupanda',
    describe: 'Gấu panda',
    img: '/emoji/7.gif',
    length: 93,
  },
  {
    id: 8,
    name: 'babysoldier',
    describe: 'Baby Solider',
    img: '/emoji/8.gif',
    length: 82,
  },
  {
    id: 9,
    name: 'gif',
    describe: 'Random Gif',
    img: '/emoji/9.gif',
    length: 15,
  },
];
